/*
 * index.java
 *
 * Created on Jul 1, 2019, 1:27:11 PM
 */
/**
 *
 * @author ANKIT
 */
public class index extends javax.swing.JFrame {
    private static String action="";
    private static double num1=0;
    private static double num2=0;
    private static double result=0;

    /** Creates new form index */
    public index() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtval = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Dot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        jLabel1.setText("<html> <head> </head>  <body> <h1><b>Simple Calculator</b></h1> </body> </html>");

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        jButton1.setText("CLR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Dot.setText(".");
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(txtval))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn4)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn5)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn6)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMinus))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn1)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn2)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn3)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPlus))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btn0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btn7)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn8)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn9)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMultiply))))
                            .addGap(12, 12, 12))))
                .addGap(18, 18, 18)
                .addComponent(Dot)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btnPlus)
                    .addComponent(Dot))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btnMinus))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnMultiply))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnEqual)
                    .addComponent(jButton1)
                    .addComponent(btnDivide))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

                                   

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn1.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {                                          
        action="/";
        num1=Double.valueOf(txtval.getText());
        txtval.setText("");
    }                                         

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn2.getText();
        txtval.setText(str);  // TODO add your handling code here:
    }                                    

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn3.getText();
        txtval.setText(str); // TODO add your handling code here:
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn4.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn5.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn6.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn7.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn8.getText();
        txtval.setText(str);// TODO add your handling code here:
    }                                    

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn9.getText();
        txtval.setText(str); // TODO add your handling code here:
    }                                    

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String str=txtval.getText()+btn0.getText();
        txtval.setText(str); // TODO add your handling code here:
    }                                    

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {                                        
        action="+";
        num1=Double.valueOf(txtval.getText());
        txtval.setText("");// TODO add your handling code here:
    }                                       

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        action="-";
        num1=Double.valueOf(txtval.getText());
        txtval.setText("");// TODO add your handling code here:
    }                                        

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {                                            
        action="*";
        num1=Double.valueOf(txtval.getText());
        txtval.setText("");// TODO add your handling code here:
    }                                           

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {                                         

        num2=Integer.valueOf(txtval.getText());
        if(action=="+"){
            result=(double)(num1+num2);
        }
        else if(action=="-"){
            result=(double)(num1-num2);
        }
        else if(action=="*"){
            result=(double)(num1*num2);
        }
        else if(action=="/"){
            result=(double)(num1/num2);
        }
        txtval.setText(String.valueOf(result)); 
           // TODO add your handling code here:
    }                                        

    private void CLRActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtval.setText("");// TODO add your handling code here:
    }                                        

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {                                    
       String str=txtval.getText()+Dot.getText();
       txtval.setText(str);// TODO add your handling code here:
    }  
    private void SqrtActionPerformed(java.awt.event.ActionEvent evt) {

       double a=Double.valueOf(txtval.getText());
       a=Math.sqrt(a);
       txtval.setText(String.valueOf(a));// TODO add your handling code here:
    }
    private void SqrActionPerformed(java.awt.event.ActionEvent evt) {
        double a=Double.valueOf(txtval.getText());
        a=Math.pow(a,2);
        txtval.setText(String.valueOf(a)); // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new index().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton Dot;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtval;
    // End of variables declaration                   
}
